### ISSUE TITLE
Typescript error on tabNavigator

### ISSUE THREAD

**Issue by titicarabina** [roninoss/create-expo-stack#260]
I have installed a project with nativewind , firebase and drawer + tabs navigator , and on drawer-navigator.tsx there is  a typescript error : 

Type '({ navigation }: Props) => Element' is not assignable to type 'ScreenComponentType<ParamListBase, "TabNavigator"> | undefined'.
  Type '({ navigation }: Props) => Element' is not assignable to type 'FunctionComponent<{}>'.
    Types of parameters '__0' and 'props' are incompatible.
      Type '{}' is missing the following properties from type 'Props': navigation, route

Also if you don't use the same name on the Drawer.Screen for TabNavigator it throws another error : Type '"Tabs"' is not assignable to type '"TabNavigator"'. , You can fix this by making sure the name is the same with the component.

**Comment by titicarabina** [comment]
I solved the issue by doing so in tab-nagivator.tsx 

type Props = StackScreenProps<RootStackParamList, 'TabNavigator'> | any;

**Comment by danstepanov** [comment]
Thanks for flagging this! Would you like to submit a PR?

**Comment by titicarabina** [comment]
That would be nice if i can do it . It;s my first PR , can you guide me please? Thank you! Appreciate your work

**Comment by danstepanov** [comment]
@titicarabina this is the file you'll want to update https://github.com/danstepanov/create-expo-stack/blob/94601f1687fd0703c0a9b6e43239f971c9e85df6/cli/src/templates/packages/react-navigation/navigation/tab-navigator.tsx.ejs

**Comment by danstepanov** [comment]
and here's our contributor guide https://github.com/danstepanov/create-expo-stack/blob/main/contributing.md

**Comment by titicarabina** [comment]
great , will do , Thanks!
