### ISSUE TITLE
Not working with Bun v1.0.22

### ISSUE THREAD

**Issue by danstepanov** [roninoss/create-expo-stack#316]
## Expected behavior
App should load properly after being installed via `bun ios`

## Actual behavior
App hangs on splashscreen (app icon image) upon running `cd my-expo-app`, `npx expo prebuild`, and `bun ios`

## Notes
```
 npx create-expo-stack@latest --version
2.10.2
```

```
                          _
   ___  _ __  ___   __ _ | |_  ___
  / __|| '__|/ _ \ / _` || __|/ _ \
 | (__ | |  |  __/| (_| || |_|  __/
  \___||_|   \___| \__,_| \__|\___|
   ___ __  __ _ __    ___
  / _ \\ \/ /| '_ \  / _ \
 |  __/ >  < | |_) || (_) |
  \___|/_/\_\| .__/  \___/
       _     |_|        _
  ___ | |_  __ _   ___ | | __
 / __|| __|/ _` | / __|| |/ /
 \__ \| |_| (_| || (__ |   <
 |___/ \__|\__,_| \___||_|\_\

┌  Let's get started!
│
◇  What do you want to name your project?
│  my-expo-app
│
◇  Would you like to use TypeScript with this project?
│  Yes
Good call, now using TypeScript! 🚀
│
◇
We've detected bun v1.0.22 as your preferred package manager.
Would you like to continue using it?
│  Yes
│
◇  What would you like to use for Navigation?
│  Expo Router
│
◇  What type of navigation would you like to use?
│  Drawer + Tabs
│
◇  What would you like to use for styling?
│  NativeWindUI
│
◇  Which components would you like to explore?
│  Action Sheet, Activity View, Avatar, Bottom Sheet, Context Menu, Date Picker, Dropdown Menu, Picker, Progress Indicator, Ratings Indicator,
Segmented Control, Selectable Text, Slider, Text, Toggle
You'll be styling with ease using NativeWindUI!
│
◇  What would you like to use for authentication?
│  None
No problem, skipping authentication for now.
│
◇  Do you want to setup EAS
│  No
No problem, skipping eas for now.
│
◇  Would you like to save this configuration for future use?
│  No

Your project configuration:
{
  projectName: 'my-expo-app',
  packages: [
    {
      name: 'expo-router',
      type: 'navigation',
      options: { type: 'drawer + tabs' }
    },
    {
      name: 'nativewindui',
      type: 'styling',
      options: {
        selectedComponents: [
          'action-sheet',       'activity-view',
          'avatar',             'bottom-sheet',
          'context-menu',       'date-picker',
          'dropdown-menu',      'picker',
          'progress-indicator', 'ratings-indicator',
          'segmented-control',  'selectable-text',
          'slider',             'text',
          'toggle'
        ]
      }
    }
  ],
  flags: {
    noGit: false,
    noInstall: false,
    overwrite: false,
    importAlias: true,
    packageManager: 'bun',
    eas: false
  }
}

To recreate this project, run:
  npx create-expo-stack my-expo-app --expo-router --drawer+tabs --nativewindui --bun
│
◇  Project initialized!
│
◇  Base assets copied!
│
◇  Dependencies installed!
│
◇  Latest version of Expo installed!
│
◇  Packages updated!
│
◇  Project files formatted!
│
◇  Git initialized!

Success! 🎉 Now, just run the following to get started:

1. cd my-expo-app
2. npx expo prebuild
3. bun ios

│
└  If you're looking to move even faster, I may be able to help!
- https://x.com/danstepanov
```

**Comment by sammoore** [comment]
Is this still relevant? Regardless, I think our `ajv` issue has been resolved by Bun upstream, and we could update the message that prints out when users are using bun. Acceptable versions could be identified here: https://github.com/oven-sh/bun/issues/8406#issuecomment-2158609939

**Comment by danstepanov** [comment]
we should try running a build locally using bun v1.1.12 with:
- Expo prebuild
- EAS local
- EAS cloud

Once those are confirmed to work, we can close this out and adjust the CLI messaging

**Comment by dannyhw** [comment]
testing this now

**Comment by dannyhw** [comment]
running prebuild success

<img width="932" alt="image" src="https://github.com/user-attachments/assets/3db6c5d6-082d-465a-8b18-cb2adac682f5">

**Comment by dannyhw** [comment]
Eas build android 

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/9cf2c6e9-affb-4eec-8b4d-f3ff2427e65b">

eas build ios
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/a0fc68e7-05c8-41d8-af8b-80562cbbd6ee">

**Comment by dannyhw** [comment]
running expo run:ios via bun also works 

<img width="510" alt="image" src="https://github.com/user-attachments/assets/7fa4601e-85e8-473c-b924-c22cbe379dd0">

<img width="410" alt="image" src="https://github.com/user-attachments/assets/c60c59fc-e3e1-4f77-9541-32871983e640">


running expo run:android

<img width="718" alt="image" src="https://github.com/user-attachments/assets/bc8576f8-3376-44c5-a8d1-30c2d6999b61">

<img width="356" alt="image" src="https://github.com/user-attachments/assets/c9b9d330-7edb-426a-9726-44a6f5bef71e">

**Comment by dannyhw** [comment]
local eas build ios

<img width="1182" alt="image" src="https://github.com/user-attachments/assets/59f63287-b4eb-486b-9618-3fcfbbc70d9a">

local eas build android

<img width="1248" alt="image" src="https://github.com/user-attachments/assets/5c4247a8-e9e4-4494-b49e-ba43071b2deb">

**Comment by dannyhw** [comment]
test project was generated with `myTestProject --expo-router --nativewind --bun --overwrite --eas`

**Comment by danstepanov** [comment]
@dannyhw great, can you adjust the messaging to ensure users are using the minimum requisite version of bun?

**Comment by dannyhw** [comment]
Yes will update soon
