### ISSUE TITLE
`eas build:configure -p all` fails when creating a new project 

### ISSUE THREAD

**Issue by lyt3ral** [roninoss/create-expo-stack#372]
## Expected Behavior
`eas build:configure -p all` should run after `expo-dev-launcher` has been installed 

## Current Behavior
`eas build:configure -p all` tries to execute but fails with the following error:

Failed to resolve plugin for module "expo-dev-launcher" relative to "<project_dir>"
    Error: build:configure command failed.
Error configuring EAS: {"stdout":null,"status":1,"error":null}
failed to run command: cd <project> && eas build:configure -p all

## Steps to Reproduce

1. run npx create-expo-stack@latest <project_name> --nativewindui --tabs --pnpm --eas
2. it produces the error mentioned earlier

## CES Config File

```json
{
  "cesVersion": "2.11.13",
  "projectName": "projectname",
  "packages": [
    {
      "name": "expo-router",
      "type": "navigation",
      "options": {
        "type": "tabs"
      }
    },
    {
      "name": "nativewindui",
      "type": "styling",
      "options": {
        "selectedComponents": [
          "activity-indicator",
          "activity-view",
          "avatar",
          "bottom-sheet",
          "date-picker",
          "picker",
          "progress-indicator",
          "ratings-indicator",
          "selectable-text",
          "slider",
          "text",
          "toggle",
          "action-sheet"
        ]
      }
    }
  ],
  "flags": {
    "noGit": false,
    "noInstall": false,
    "overwrite": false,
    "importAlias": true,
    "packageManager": "pnpm",
    "eas": true
  },
  "packageManager": {
    "type": "pnpm",
    "version": "9.1.2"
  },
  "os": {
    "type": "Linux",
    "platform": "linux",
    "arch": "x64",
    "kernelVersion": "6.5.0-28-generic"
  }
}
```

**Comment by dannyhw** [comment]
Weird, thanks for letting us know. Will take a look.

**Comment by dannyhw** [comment]
This seems to be specific to how pnpm handles peer dependencies since this actually works with bun for example. Should have a fix soon.

**Comment by dannyhw** [comment]
@lyt3ral will be fixed by this PR
https://github.com/roninoss/create-expo-stack/pull/373

Thanks for reporting 🙏

**Comment by lyt3ral** [comment]
thanks for looking into this 🙏🏼

**Comment by danstepanov** [comment]
thanks @dannyhw!
