### ISSUE TITLE
Customise the folder of entry point 

### ISSUE THREAD

**Issue by zhouhao27** [roninoss/create-expo-stack#388]
Got warning message when I move `app`, `components` and `assets` folder into src.

## Expected Behavior

Should not show any warning message. Don't know what will be affected.

## Current Behavior

I modified `app.json` by adding `./src` to any `assets` and I also modified the `tsconfig.json` as following:

```
 "paths": {
      "~/*": ["./src/*"]
    }
```

Then I got this warning message:

![Simulator Screenshot - iPhone 15 Pro - 2024-08-07 at 23 54 56](https://github.com/user-attachments/assets/ed43911a-ac8f-4a5d-a704-5d7d9661ddf8)

Not very sure if it will affect anything or not.

## Steps to Reproduce

1.  `npx create-expo-stack@latest myapp --expo-router --drawer+tabs --stylesheet`
2. Create a `src` folder in project root
3. move `app`, `assets` and `components` folder into `src` folder
4. Modify `app.json` and `tsconfig.json` accordingly

## CES Config File

```json
{
  "cesVersion": "2.11.16",
  "projectName": "role-auth",
  "packages": [
    {
      "name": "expo-router",
      "type": "navigation",
      "options": {
        "type": "drawer + tabs"
      }
    },
    {
      "name": "stylesheet",
      "type": "styling"
    }
  ],
  "flags": {
    "noGit": false,
    "noInstall": false,
    "overwrite": false,
    "importAlias": true,
    "packageManager": "npm",
    "eas": false
  },
  "packageManager": {
    "type": "npm",
    "version": "10.7.0"
  },
  "os": {
    "type": "Darwin",
    "platform": "darwin",
    "arch": "arm64",
    "kernelVersion": "24.0.0"
  }
}
```

**Comment by dannyhw** [comment]
Can you confirm if you've trying clearing the metro cache?

**Comment by zhouhao27** [comment]
> Can you confirm if you've trying clearing the metro cache?

You're right. I guess it's the cache issue. Everything is fine now. Thanks.
