### ISSUE TITLE
Initializing with pnpm does not work with NativeWindUI

### ISSUE THREAD

**Issue by danstepanov** [roninoss/create-expo-stack#393]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discord, in the #create-expo-stack channel.

## Expected Behavior

No errors during CLI process

## Current Behavior

<img width="1502" alt="Screenshot 2024-08-19 at 6 39 04 PM" src="https://github.com/user-attachments/assets/e2e922a9-c22a-4723-970d-f6d4552de475">

## Possible Solution

Something pertaining to authorization?

## Steps to Reproduce

`pnpm --version`: `9.6.0`
1. npx create-expo-stack@latest --nativewindui --pnpm

## CES Config File

```
{
  "cesVersion": "2.11.17",
  "projectName": "my-pnpm-app",
  "packages": [
    {
      "name": "nativewindui",
      "type": "styling",
      "options": {
        "selectedComponents": [
          "action-sheet",
          "activity-indicator",
          "activity-view",
          "avatar",
          "bottom-sheet",
          "date-picker",
          "picker",
          "progress-indicator",
          "ratings-indicator",
          "slider",
          "text",
          "toggle"
        ]
      }
    },
    {
      "name": "expo-router",
      "type": "navigation",
      "options": {
        "type": "stack"
      }
    }
  ],
  "flags": {
    "noGit": false,
    "noInstall": false,
    "overwrite": false,
    "importAlias": true,
    "packageManager": "pnpm",
    "eas": false
  },
  "packageManager": {
    "type": "pnpm",
    "version": "9.6.0"
  },
  "os": {
    "type": "Darwin",
    "platform": "darwin",
    "arch": "arm64",
    "kernelVersion": "23.6.0"
  }
}
```

**Comment by dannyhw** [comment]
Looks like the --yes is getting added to the npm registry somehow? Weird. Maybe its from the pnpm dlx command with --yes

**Comment by danstepanov** [comment]
resolved
