### ISSUE TITLE
Missing nativewindui folder when using bun

### ISSUE THREAD

**Issue by danstepanov** [roninoss/create-expo-stack#394]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discord, in the #create-expo-stack channel.

## Expected Behavior

Project should include `/components/nativewindui` directory when components are installed

## Current Behavior

![Screenshot 2024-08-19 at 7 04 26 PM](https://github.com/user-attachments/assets/7a21b20e-5597-4965-8010-7034438998f4)
<img width="505" alt="Screenshot 2024-08-19 at 7 04 35 PM" src="https://github.com/user-attachments/assets/acf56701-9c4c-45d0-851c-493a0bc4f285">

## Possible Solution

Something pertaining to the NWUI CLI?

## Steps to Reproduce

`bun --version`: `1.0.22`
1. npx create-expo-stack@latest --nativewindui --bun

## CES Config File

```
{
  "cesVersion": "2.11.17",
  "projectName": "my-expo-app",
  "packages": [
    {
      "name": "nativewindui",
      "type": "styling",
      "options": {
        "selectedComponents": [
          "action-sheet",
          "activity-indicator",
          "activity-view",
          "avatar",
          "bottom-sheet",
          "date-picker",
          "picker",
          "progress-indicator",
          "ratings-indicator",
          "slider",
          "text",
          "toggle"
        ]
      }
    },
    {
      "name": "expo-router",
      "type": "navigation",
      "options": {
        "type": "stack"
      }
    }
  ],
  "flags": {
    "noGit": false,
    "noInstall": false,
    "overwrite": false,
    "importAlias": true,
    "packageManager": "bun",
    "eas": false
  },
  "packageManager": {
    "type": "bun",
    "version": "1.0.22"
  },
  "os": {
    "type": "Darwin",
    "platform": "darwin",
    "arch": "arm64",
    "kernelVersion": "23.6.0"
  }
}
```

**Comment by sammoore** [comment]
@danstepanov this is an issue with that version of Bun. I've verified:

- Reproduced the issue on Bun 1.0.22
- No issues on Bun 1.1.17
- No issues on Bun 1.1.24

Given that Bun's stability wasn't great on 1.0, they are shipping fast and breaking things, and have no defined support policy, I personally don't think we should workaround new issues in Bun 1.0

**Comment by dannyhw** [comment]
Yeah we already changed our recommendation to use the latest bun version. I can make a change to the warning to show for older versions like this aswell as the ones effected by the ajv stuff.

**Comment by danstepanov** [comment]
worked with latest
