### ISSUE TITLE
App is not starting

### ISSUE THREAD

**Issue by RahulDey12** [roninoss/create-expo-stack#414]
I am new to this ecosystem and when I am creating the app with nativewind and react-navigation or even with expo router it's installing and ran but not starting the app it's stuck on splash screen

## Steps to Reproduce

1. Just create and run `npm run android`

## CES Config File

```json
{
  "cesVersion": "2.11.24",
  "projectName": "test-expo-router",
  "packages": [
    {
      "name": "expo-router",
      "type": "navigation",
      "options": {
        "type": "drawer + tabs"
      }
    },
    {
      "name": "nativewind",
      "type": "styling"
    }
  ],
  "flags": {
    "noGit": false,
    "noInstall": false,
    "overwrite": false,
    "importAlias": true,
    "packageManager": "npm",
    "eas": false
  },
  "packageManager": {
    "type": "npm",
    "version": "10.5.0"
  },
  "os": {
    "type": "Darwin",
    "platform": "darwin",
    "arch": "arm64",
    "kernelVersion": "23.6.0"
  }
}
```

**Comment by ttmachado** [comment]
Run `npx expo prebuild --clean` and try again. I believe this should be one of the instructions displayed after the project creation but it looks like it's not being printed out.

**Comment by dannyhw** [comment]
technically prebuild isn't required for that setup since expo router works in expo go

**Comment by RahulDey12** [comment]
after changing the nativewind version from `next` to `4.1.7` I am getting a white screen with this
<img width="475" alt="image" src="https://github.com/user-attachments/assets/f164e92a-274a-4d6d-9e78-de2e81836c83">

**Comment by RahulDey12** [comment]
It's working with nativewind 4.1.7 thanks @dannyhw
