### ISSUE TITLE
Cant create java-script project all time give - type-Script

### ISSUE THREAD

**Issue by Ahmed-Ibrahim-Anter** [roninoss/create-expo-stack#418]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discord, in the #create-expo-stack channel.

cant create java-script app
## Expected Behavior

when i choose typescript no should create js app
## Current Behavior

i choose typescript  no but app created in typescript 
## Possible Solution
add js template

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dannyhw** [comment]
Being typescript only is intentional as part of an opinionated stack
