### ISSUE TITLE
Fresh stack with --nativewind fails to load due to a dependency error

### ISSUE THREAD

**Issue by MrPiao** [roninoss/create-expo-stack#423]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discord, in the #create-expo-stack channel.

## Expected Behavior
Fresh stack from running `npx create-expo-stack@latest --nativewind` should work out of the box.

## Current Behavior
App fails to initialize due to "Error: Unable to resolve module `react-native-safe-area-context`"
![image](https://github.com/user-attachments/assets/61f69311-d347-4023-ae8f-76b12e6a43e5)

## Possible Solution

`npx expo install react-native-safe-area-context` fixes it.

This also seems like it could be a bug in NativeWind as the above library seems like it should be a dependency of `react-native-css-interop`

**Comment by dannyhw** [comment]
Hey thanks for the report, i think #421 might be the fix for this actually

**Comment by danstepanov** [comment]
Closing this as fixed

**Comment by joypatel04** [comment]
@danstepanov Not sure but create a new app today and facing this issue.
