### ISSUE TITLE
Received an error when choosing 'no' to automatically create an EAS project

### ISSUE THREAD

**Issue by RushilJalal** [roninoss/create-expo-stack#428]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discord, in the #create-expo-stack channel.

## Expected Behavior

An error should not have occured on selecting 'no' to automatically creating an EAS project.

## Current Behavior

I received an unexpected error

![image](https://github.com/user-attachments/assets/c84eb772-ee30-4787-aeac-757001701be9)

## Possible Solution

Look into the reason why I received an error. Possibly remove the error if there's nothing wrong.

## Steps to Reproduce

1. Create a project using `create-expo-stack`
2. Select 'no' for the question `Would you like to automatically create an EAS project for @username?`

## CES Config File

```json
{
  "cesVersion": "2.11.25",
  "projectName": "n",
  "packages": [
    {
      "name": "expo-router",
      "type": "navigation",
      "options": {
        "type": "stack"
      }
    },
    {
      "name": "nativewind",
      "type": "styling"
    },
    {
      "name": "supabase",
      "type": "authentication"
    }
  ],
  "flags": {
    "noGit": false,
    "noInstall": false,
    "overwrite": false,
    "importAlias": true,
    "packageManager": "npm",
    "eas": true
  },
  "packageManager": {
    "type": "npm",
    "version": "10.9.0"
  },
  "os": {
    "type": "Windows_NT",
    "platform": "win32",
    "arch": "x64",
    "kernelVersion": "10.0.22631"
  }
}
```

**Comment by dannyhw** [comment]
if you choose to setup eas but then say no when it asks to setup eas for you then that seems like its a fail state. Is that not what you would expect? Could you explain what you would expect to happen?

**Comment by dannyhw** [comment]
Closing since there's no response, let me know if we should reopen
