### ISSUE TITLE
Please add Redux and Redux ToolKit Option 

### ISSUE THREAD

**Issue by vijaypotnuru** [roninoss/create-expo-stack#439]
Please add Redux and Redux ToolKit setup Option

**Comment by danstepanov** [comment]
There's a PR for it, requires some changes that @mrzachnugent requested

**Comment by vijaypotnuru** [comment]
and also please add tanStack Query -(React Query), it can be usefull

**Comment by danstepanov** [comment]
#417 for reference, if you'd like to request something else, please use the discord channel for create expo stack. The Github issue are only for issues.
